# Generated by Django 5.2.13 on 2026-04-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_detectiontask_error_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_progress", "正在检测中"),
                    ("completed", "检测已完成"),
                    ("failed", "检测失败"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="detectiontask",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("in_progress", "进行中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
