# Generated by Django 5.2.13 on 2026-04-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_review_result_split"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemanagement",
            name="file_type",
            field=models.CharField(max_length=255),
        ),
    ]
