# Generated by Django 5.2.13 on 2026-04-25 00:00

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_filemanagement_file_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceReviewRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("task_type", models.CharField(choices=[("paper", "Paper"), ("review", "Review")], db_index=True, max_length=20)),
                ("request_time", models.DateTimeField(db_index=True, default=django.utils.timezone.localtime)),
                ("status1", models.CharField(choices=[("pending", "Pending"), ("in_progress", "In Progress"), ("completed", "Completed")], default="pending", max_length=50)),
                ("status2", models.CharField(choices=[("pending", "Pending"), ("refused", "Refused"), ("accepted", "Accepted")], default="pending", max_length=50)),
                ("reason", models.TextField(blank=True, default="")),
                ("check_reason", models.TextField(blank=True, default="")),
                ("review_start_time", models.DateTimeField(blank=True, null=True)),
                ("review_end_time", models.DateTimeField(blank=True, null=True)),
                ("detection_task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resource_review_requests", to="core.detectiontask")),
                ("organization", models.ForeignKey(blank=True, db_index=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="core.organization")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resource_review_requests", to="core.user")),
                ("reviewers", models.ManyToManyField(blank=True, related_name="resource_requests_to_review", to="core.user")),
                ("selected_files", models.ManyToManyField(blank=True, related_name="resource_review_requests", to="core.filemanagement")),
            ],
        ),
        migrations.CreateModel(
            name="ResourceManualReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("undo", "Undo"), ("completed", "Completed")], default="undo", max_length=50)),
                ("review_time", models.DateTimeField(db_index=True, default=django.utils.timezone.localtime)),
                ("result_payload", models.JSONField(blank=True, null=True)),
                ("conclusion", models.TextField(blank=True, default="")),
                ("review_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="manual_reviews", to="core.resourcereviewrequest")),
                ("reviewer", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="resource_manual_reviews", to="core.user")),
            ],
            options={
                "unique_together": {("review_request", "reviewer")},
            },
        ),
    ]
