# Generated by Django 5.2.13 on 2026-05-10 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_resource_manual_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(help_text='模型实名(如 deepseek-chat)', max_length=255, unique=True)),
                ('display_name', models.CharField(help_text='展示给用户看的名称(如 DeepSeek V3)', max_length=255)),
                ('provider', models.CharField(default='openai_compat', help_text='平台供应商标识', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='是否对用户开放可用')),
                ('description', models.TextField(blank=True, help_text='模型特点描述', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='detectiontask',
            name='llm_model_name',
            field=models.CharField(blank=True, help_text='用户选择的大模型名称', max_length=255, null=True),
        ),
    ]
