# Generated by Codex on 2026-05-10

from django.db import migrations, models


def seed_fastdetect_config(apps, schema_editor):
    LLMModel = apps.get_model("core", "LLMModel")
    LLMModel.objects.get_or_create(
        model_name="fast-detect(llama3-8b/llama3-8b-instruct)",
        defaults={
            "display_name": "FastDetect AIGC 检测",
            "provider": "fastdetect",
            "model_type": "fastdetect",
            "endpoint": "https://api.fastdetect.net/api/detect",
            "api_key": "",
            "is_active": True,
            "description": "用于论文/Review 段落 AIGC 概率检测。API Key 可在管理端配置。",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_llmmodel_detectiontask_llm_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmodel",
            name="api_key",
            field=models.CharField(blank=True, help_text="API Key", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="endpoint",
            field=models.CharField(blank=True, help_text="API Endpoint", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="model_type",
            field=models.CharField(
                choices=[("chat", "Chat LLM"), ("fastdetect", "FastDetect")],
                db_index=True,
                default="chat",
                help_text="模型用途类型：chat 为对话模型，fastdetect 为 AIGC 段落检测服务",
                max_length=30,
            ),
        ),
        migrations.RunPython(seed_fastdetect_config, migrations.RunPython.noop),
    ]
