# Generated by Codex on 2026-05-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_llmmodel_runtime_config"),
    ]

    operations = [
        migrations.AlterField(
            model_name="detectionresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "排队中"),
                    ("in_progress", "正在检测中"),
                    ("completed", "检测已完成"),
                    ("failed", "检测失败"),
                ],
                default="in_progress",
                max_length=20,
            ),
        ),
    ]
