# Generated by Django 5.2.13 on 2026-06-08 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_detectionresult_pending_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmmodel",
            name="model_name",
            field=models.CharField(
                db_index=True,
                help_text="模型实名(如 deepseek-chat)。允许重复：同一检测器可配多把 key 做 fallback。",
                max_length=255,
            ),
        ),
    ]
