# Generated by Django 5.2.13 on 2026-06-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_alter_llmmodel_model_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmmodel",
            name="credit_total",
            field=models.FloatField(
                blank=True, help_text="fastdetect 额度总量", null=True
            ),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="credit_used",
            field=models.FloatField(
                blank=True, help_text="fastdetect 额度已用量", null=True
            ),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="health_checked_at",
            field=models.DateTimeField(
                blank=True, help_text="上次健康探测时间", null=True
            ),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="health_detail",
            field=models.TextField(
                blank=True, help_text="健康探测返回的详情消息", null=True
            ),
        ),
        migrations.AddField(
            model_name="llmmodel",
            name="health_status",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("available", "Available"),
                    ("exhausted", "Exhausted"),
                    ("invalid", "Invalid"),
                    ("error", "Error"),
                ],
                default="unknown",
                help_text="针对 fastdetect 模型的健康探测状态",
                max_length=20,
            ),
        ),
    ]
